// Code generated by protoc-gen-go.
// source: controllers/proto/api.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	controllers/proto/api.proto

It has these top-level messages:
	ContactResponse
	AuthorizeContactRequest
	ConnectServiceAndMirror
	MirrorFindRequest
	MirrorGetRequest
	MirrorGetResponse
	ServiceGetRequest
	ServiceGetResponse
	Contact
	Service
	Mirror
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type ContactResponse struct {
	Token   string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Contact *Contact `protobuf:"bytes,2,opt,name=contact" json:"contact,omitempty"`
}

func (m *ContactResponse) Reset()                    { *m = ContactResponse{} }
func (m *ContactResponse) String() string            { return proto1.CompactTextString(m) }
func (*ContactResponse) ProtoMessage()               {}
func (*ContactResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ContactResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ContactResponse) GetContact() *Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

type AuthorizeContactRequest struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *AuthorizeContactRequest) Reset()                    { *m = AuthorizeContactRequest{} }
func (m *AuthorizeContactRequest) String() string            { return proto1.CompactTextString(m) }
func (*AuthorizeContactRequest) ProtoMessage()               {}
func (*AuthorizeContactRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuthorizeContactRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthorizeContactRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ConnectServiceAndMirror struct {
	MirrorId   int32 `protobuf:"varint,1,opt,name=mirror_id,json=mirrorId" json:"mirror_id,omitempty"`
	EndpointId int32 `protobuf:"varint,2,opt,name=endpoint_id,json=endpointId" json:"endpoint_id,omitempty"`
}

func (m *ConnectServiceAndMirror) Reset()                    { *m = ConnectServiceAndMirror{} }
func (m *ConnectServiceAndMirror) String() string            { return proto1.CompactTextString(m) }
func (*ConnectServiceAndMirror) ProtoMessage()               {}
func (*ConnectServiceAndMirror) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ConnectServiceAndMirror) GetMirrorId() int32 {
	if m != nil {
		return m.MirrorId
	}
	return 0
}

func (m *ConnectServiceAndMirror) GetEndpointId() int32 {
	if m != nil {
		return m.EndpointId
	}
	return 0
}

type MirrorFindRequest struct {
	ClientToken string `protobuf:"bytes,1,opt,name=client_token,json=clientToken" json:"client_token,omitempty"`
}

func (m *MirrorFindRequest) Reset()                    { *m = MirrorFindRequest{} }
func (m *MirrorFindRequest) String() string            { return proto1.CompactTextString(m) }
func (*MirrorFindRequest) ProtoMessage()               {}
func (*MirrorFindRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MirrorFindRequest) GetClientToken() string {
	if m != nil {
		return m.ClientToken
	}
	return ""
}

type MirrorGetRequest struct {
	Limit  int32 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Offset int32 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
}

func (m *MirrorGetRequest) Reset()                    { *m = MirrorGetRequest{} }
func (m *MirrorGetRequest) String() string            { return proto1.CompactTextString(m) }
func (*MirrorGetRequest) ProtoMessage()               {}
func (*MirrorGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MirrorGetRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *MirrorGetRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type MirrorGetResponse struct {
	Mirrors []*Mirror `protobuf:"bytes,1,rep,name=mirrors" json:"mirrors,omitempty"`
}

func (m *MirrorGetResponse) Reset()                    { *m = MirrorGetResponse{} }
func (m *MirrorGetResponse) String() string            { return proto1.CompactTextString(m) }
func (*MirrorGetResponse) ProtoMessage()               {}
func (*MirrorGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MirrorGetResponse) GetMirrors() []*Mirror {
	if m != nil {
		return m.Mirrors
	}
	return nil
}

type ServiceGetRequest struct {
	Limit  int32 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Offset int32 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
}

func (m *ServiceGetRequest) Reset()                    { *m = ServiceGetRequest{} }
func (m *ServiceGetRequest) String() string            { return proto1.CompactTextString(m) }
func (*ServiceGetRequest) ProtoMessage()               {}
func (*ServiceGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ServiceGetRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ServiceGetRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ServiceGetResponse struct {
	Services []*Service `protobuf:"bytes,1,rep,name=services" json:"services,omitempty"`
}

func (m *ServiceGetResponse) Reset()                    { *m = ServiceGetResponse{} }
func (m *ServiceGetResponse) String() string            { return proto1.CompactTextString(m) }
func (*ServiceGetResponse) ProtoMessage()               {}
func (*ServiceGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ServiceGetResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type Contact struct {
	Id       int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password" json:"password,omitempty"`
	Admin    bool   `protobuf:"varint,5,opt,name=admin" json:"admin,omitempty"`
}

func (m *Contact) Reset()                    { *m = Contact{} }
func (m *Contact) String() string            { return proto1.CompactTextString(m) }
func (*Contact) ProtoMessage()               {}
func (*Contact) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Contact) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Contact) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Contact) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Contact) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Contact) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

type Service struct {
	Id                 int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name               string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Storage            int64  `protobuf:"varint,3,opt,name=storage" json:"storage,omitempty"`
	TrafficConsumption int64  `protobuf:"varint,4,opt,name=traffic_consumption,json=trafficConsumption" json:"traffic_consumption,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto1.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Service) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetStorage() int64 {
	if m != nil {
		return m.Storage
	}
	return 0
}

func (m *Service) GetTrafficConsumption() int64 {
	if m != nil {
		return m.TrafficConsumption
	}
	return 0
}

type Mirror struct {
	Id               int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	ContactId        int32    `protobuf:"varint,2,opt,name=contact_id,json=contactId" json:"contact_id,omitempty"`
	Ipv4             string   `protobuf:"bytes,3,opt,name=ipv4" json:"ipv4,omitempty"`
	Ipv6             string   `protobuf:"bytes,4,opt,name=ipv6" json:"ipv6,omitempty"`
	Name             string   `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	Domain           string   `protobuf:"bytes,6,opt,name=domain" json:"domain,omitempty"`
	ClientToken      string   `protobuf:"bytes,7,opt,name=client_token,json=clientToken" json:"client_token,omitempty"`
	CreatedAt        int64    `protobuf:"varint,8,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	Bandwidth        int64    `protobuf:"varint,9,opt,name=bandwidth" json:"bandwidth,omitempty"`
	Traffic          int64    `protobuf:"varint,10,opt,name=traffic" json:"traffic,omitempty"`
	AvailableStorage int64    `protobuf:"varint,11,opt,name=available_storage,json=availableStorage" json:"available_storage,omitempty"`
	Service          *Service `protobuf:"bytes,12,opt,name=service" json:"service,omitempty"`
	ServiceEndpoint  *Mirror  `protobuf:"bytes,13,opt,name=service_endpoint,json=serviceEndpoint" json:"service_endpoint,omitempty"`
	LocalDestination string   `protobuf:"bytes,14,opt,name=local_destination,json=localDestination" json:"local_destination,omitempty"`
}

func (m *Mirror) Reset()                    { *m = Mirror{} }
func (m *Mirror) String() string            { return proto1.CompactTextString(m) }
func (*Mirror) ProtoMessage()               {}
func (*Mirror) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Mirror) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Mirror) GetContactId() int32 {
	if m != nil {
		return m.ContactId
	}
	return 0
}

func (m *Mirror) GetIpv4() string {
	if m != nil {
		return m.Ipv4
	}
	return ""
}

func (m *Mirror) GetIpv6() string {
	if m != nil {
		return m.Ipv6
	}
	return ""
}

func (m *Mirror) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Mirror) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Mirror) GetClientToken() string {
	if m != nil {
		return m.ClientToken
	}
	return ""
}

func (m *Mirror) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Mirror) GetBandwidth() int64 {
	if m != nil {
		return m.Bandwidth
	}
	return 0
}

func (m *Mirror) GetTraffic() int64 {
	if m != nil {
		return m.Traffic
	}
	return 0
}

func (m *Mirror) GetAvailableStorage() int64 {
	if m != nil {
		return m.AvailableStorage
	}
	return 0
}

func (m *Mirror) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *Mirror) GetServiceEndpoint() *Mirror {
	if m != nil {
		return m.ServiceEndpoint
	}
	return nil
}

func (m *Mirror) GetLocalDestination() string {
	if m != nil {
		return m.LocalDestination
	}
	return ""
}

func init() {
	proto1.RegisterType((*ContactResponse)(nil), "proto.ContactResponse")
	proto1.RegisterType((*AuthorizeContactRequest)(nil), "proto.AuthorizeContactRequest")
	proto1.RegisterType((*ConnectServiceAndMirror)(nil), "proto.ConnectServiceAndMirror")
	proto1.RegisterType((*MirrorFindRequest)(nil), "proto.MirrorFindRequest")
	proto1.RegisterType((*MirrorGetRequest)(nil), "proto.MirrorGetRequest")
	proto1.RegisterType((*MirrorGetResponse)(nil), "proto.MirrorGetResponse")
	proto1.RegisterType((*ServiceGetRequest)(nil), "proto.ServiceGetRequest")
	proto1.RegisterType((*ServiceGetResponse)(nil), "proto.ServiceGetResponse")
	proto1.RegisterType((*Contact)(nil), "proto.Contact")
	proto1.RegisterType((*Service)(nil), "proto.Service")
	proto1.RegisterType((*Mirror)(nil), "proto.Mirror")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ContactService service

type ContactServiceClient interface {
	Create(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*ContactResponse, error)
	Update(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*ContactResponse, error)
	Get(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*ContactResponse, error)
	Authorize(ctx context.Context, in *AuthorizeContactRequest, opts ...grpc.CallOption) (*ContactResponse, error)
}

type contactServiceClient struct {
	cc *grpc.ClientConn
}

func NewContactServiceClient(cc *grpc.ClientConn) ContactServiceClient {
	return &contactServiceClient{cc}
}

func (c *contactServiceClient) Create(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*ContactResponse, error) {
	out := new(ContactResponse)
	err := grpc.Invoke(ctx, "/proto.ContactService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) Update(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*ContactResponse, error) {
	out := new(ContactResponse)
	err := grpc.Invoke(ctx, "/proto.ContactService/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) Get(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*ContactResponse, error) {
	out := new(ContactResponse)
	err := grpc.Invoke(ctx, "/proto.ContactService/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) Authorize(ctx context.Context, in *AuthorizeContactRequest, opts ...grpc.CallOption) (*ContactResponse, error) {
	out := new(ContactResponse)
	err := grpc.Invoke(ctx, "/proto.ContactService/Authorize", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ContactService service

type ContactServiceServer interface {
	Create(context.Context, *Contact) (*ContactResponse, error)
	Update(context.Context, *Contact) (*ContactResponse, error)
	Get(context.Context, *Contact) (*ContactResponse, error)
	Authorize(context.Context, *AuthorizeContactRequest) (*ContactResponse, error)
}

func RegisterContactServiceServer(s *grpc.Server, srv ContactServiceServer) {
	s.RegisterService(&_ContactService_serviceDesc, srv)
}

func _ContactService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Contact)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ContactService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).Create(ctx, req.(*Contact))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Contact)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ContactService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).Update(ctx, req.(*Contact))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Contact)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ContactService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).Get(ctx, req.(*Contact))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ContactService/Authorize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).Authorize(ctx, req.(*AuthorizeContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContactService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ContactService",
	HandlerType: (*ContactServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ContactService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ContactService_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ContactService_Get_Handler,
		},
		{
			MethodName: "Authorize",
			Handler:    _ContactService_Authorize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controllers/proto/api.proto",
}

// Client API for MirrorService service

type MirrorServiceClient interface {
	Get(ctx context.Context, in *MirrorGetRequest, opts ...grpc.CallOption) (*MirrorGetResponse, error)
	Find(ctx context.Context, in *MirrorFindRequest, opts ...grpc.CallOption) (*Mirror, error)
	FindById(ctx context.Context, in *Mirror, opts ...grpc.CallOption) (*Mirror, error)
	UpdateById(ctx context.Context, in *Mirror, opts ...grpc.CallOption) (*Mirror, error)
	Connect(ctx context.Context, in *ConnectServiceAndMirror, opts ...grpc.CallOption) (*Mirror, error)
	Create(ctx context.Context, in *Mirror, opts ...grpc.CallOption) (*Mirror, error)
}

type mirrorServiceClient struct {
	cc *grpc.ClientConn
}

func NewMirrorServiceClient(cc *grpc.ClientConn) MirrorServiceClient {
	return &mirrorServiceClient{cc}
}

func (c *mirrorServiceClient) Get(ctx context.Context, in *MirrorGetRequest, opts ...grpc.CallOption) (*MirrorGetResponse, error) {
	out := new(MirrorGetResponse)
	err := grpc.Invoke(ctx, "/proto.MirrorService/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mirrorServiceClient) Find(ctx context.Context, in *MirrorFindRequest, opts ...grpc.CallOption) (*Mirror, error) {
	out := new(Mirror)
	err := grpc.Invoke(ctx, "/proto.MirrorService/Find", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mirrorServiceClient) FindById(ctx context.Context, in *Mirror, opts ...grpc.CallOption) (*Mirror, error) {
	out := new(Mirror)
	err := grpc.Invoke(ctx, "/proto.MirrorService/FindById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mirrorServiceClient) UpdateById(ctx context.Context, in *Mirror, opts ...grpc.CallOption) (*Mirror, error) {
	out := new(Mirror)
	err := grpc.Invoke(ctx, "/proto.MirrorService/UpdateById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mirrorServiceClient) Connect(ctx context.Context, in *ConnectServiceAndMirror, opts ...grpc.CallOption) (*Mirror, error) {
	out := new(Mirror)
	err := grpc.Invoke(ctx, "/proto.MirrorService/Connect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mirrorServiceClient) Create(ctx context.Context, in *Mirror, opts ...grpc.CallOption) (*Mirror, error) {
	out := new(Mirror)
	err := grpc.Invoke(ctx, "/proto.MirrorService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MirrorService service

type MirrorServiceServer interface {
	Get(context.Context, *MirrorGetRequest) (*MirrorGetResponse, error)
	Find(context.Context, *MirrorFindRequest) (*Mirror, error)
	FindById(context.Context, *Mirror) (*Mirror, error)
	UpdateById(context.Context, *Mirror) (*Mirror, error)
	Connect(context.Context, *ConnectServiceAndMirror) (*Mirror, error)
	Create(context.Context, *Mirror) (*Mirror, error)
}

func RegisterMirrorServiceServer(s *grpc.Server, srv MirrorServiceServer) {
	s.RegisterService(&_MirrorService_serviceDesc, srv)
}

func _MirrorService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MirrorGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MirrorServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MirrorService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MirrorServiceServer).Get(ctx, req.(*MirrorGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MirrorService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MirrorFindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MirrorServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MirrorService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MirrorServiceServer).Find(ctx, req.(*MirrorFindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MirrorService_FindById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mirror)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MirrorServiceServer).FindById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MirrorService/FindById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MirrorServiceServer).FindById(ctx, req.(*Mirror))
	}
	return interceptor(ctx, in, info, handler)
}

func _MirrorService_UpdateById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mirror)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MirrorServiceServer).UpdateById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MirrorService/UpdateById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MirrorServiceServer).UpdateById(ctx, req.(*Mirror))
	}
	return interceptor(ctx, in, info, handler)
}

func _MirrorService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectServiceAndMirror)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MirrorServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MirrorService/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MirrorServiceServer).Connect(ctx, req.(*ConnectServiceAndMirror))
	}
	return interceptor(ctx, in, info, handler)
}

func _MirrorService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mirror)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MirrorServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MirrorService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MirrorServiceServer).Create(ctx, req.(*Mirror))
	}
	return interceptor(ctx, in, info, handler)
}

var _MirrorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MirrorService",
	HandlerType: (*MirrorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _MirrorService_Get_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _MirrorService_Find_Handler,
		},
		{
			MethodName: "FindById",
			Handler:    _MirrorService_FindById_Handler,
		},
		{
			MethodName: "UpdateById",
			Handler:    _MirrorService_UpdateById_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _MirrorService_Connect_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _MirrorService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controllers/proto/api.proto",
}

// Client API for ServiceService service

type ServiceServiceClient interface {
	Get(ctx context.Context, in *ServiceGetRequest, opts ...grpc.CallOption) (*ServiceGetResponse, error)
	Update(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Service, error)
	Find(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Service, error)
	Create(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Service, error)
}

type serviceServiceClient struct {
	cc *grpc.ClientConn
}

func NewServiceServiceClient(cc *grpc.ClientConn) ServiceServiceClient {
	return &serviceServiceClient{cc}
}

func (c *serviceServiceClient) Get(ctx context.Context, in *ServiceGetRequest, opts ...grpc.CallOption) (*ServiceGetResponse, error) {
	out := new(ServiceGetResponse)
	err := grpc.Invoke(ctx, "/proto.ServiceService/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceServiceClient) Update(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Service, error) {
	out := new(Service)
	err := grpc.Invoke(ctx, "/proto.ServiceService/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceServiceClient) Find(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Service, error) {
	out := new(Service)
	err := grpc.Invoke(ctx, "/proto.ServiceService/Find", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceServiceClient) Create(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Service, error) {
	out := new(Service)
	err := grpc.Invoke(ctx, "/proto.ServiceService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ServiceService service

type ServiceServiceServer interface {
	Get(context.Context, *ServiceGetRequest) (*ServiceGetResponse, error)
	Update(context.Context, *Service) (*Service, error)
	Find(context.Context, *Service) (*Service, error)
	Create(context.Context, *Service) (*Service, error)
}

func RegisterServiceServiceServer(s *grpc.Server, srv ServiceServiceServer) {
	s.RegisterService(&_ServiceService_serviceDesc, srv)
}

func _ServiceService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ServiceService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServiceServer).Get(ctx, req.(*ServiceGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ServiceService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServiceServer).Update(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ServiceService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServiceServer).Find(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ServiceService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServiceServer).Create(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ServiceService",
	HandlerType: (*ServiceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ServiceService_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ServiceService_Update_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _ServiceService_Find_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ServiceService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controllers/proto/api.proto",
}

func init() { proto1.RegisterFile("controllers/proto/api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 944 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x55, 0x5d, 0x6e, 0x23, 0x45,
	0x10, 0x96, 0xed, 0xf8, 0xaf, 0x9c, 0x78, 0xed, 0xce, 0xe2, 0xcc, 0x3a, 0x01, 0xc2, 0xbc, 0x60,
	0x05, 0x29, 0x86, 0x80, 0x22, 0x14, 0x21, 0xb4, 0xde, 0xc0, 0x06, 0x0b, 0x2d, 0x82, 0x59, 0x10,
	0x8f, 0x56, 0x67, 0xba, 0x9d, 0xb4, 0x18, 0x77, 0x0f, 0x33, 0xed, 0x2c, 0xb0, 0xca, 0x0b, 0x57,
	0xe0, 0x22, 0xdc, 0x81, 0x23, 0xf0, 0xc2, 0x01, 0x78, 0xe0, 0x18, 0x68, 0xba, 0xab, 0xc7, 0x33,
	0x36, 0x61, 0x03, 0x4f, 0xd3, 0x55, 0xd5, 0xf5, 0x55, 0x75, 0x7d, 0x55, 0x35, 0xb0, 0x1f, 0x2a,
	0xa9, 0x13, 0x15, 0x45, 0x3c, 0x49, 0xc7, 0x71, 0xa2, 0xb4, 0x1a, 0xd3, 0x58, 0x1c, 0x9b, 0x13,
	0xa9, 0x9b, 0xcf, 0xf0, 0xe0, 0x4a, 0xa9, 0xab, 0x88, 0x67, 0x86, 0x31, 0x95, 0x52, 0x69, 0xaa,
	0x85, 0x92, 0xa9, 0xbd, 0xe4, 0x7f, 0x05, 0x0f, 0xce, 0x95, 0xd4, 0x34, 0xd4, 0x01, 0x4f, 0x63,
	0x25, 0x53, 0x4e, 0x1e, 0x42, 0x5d, 0xab, 0xef, 0xb8, 0xf4, 0x2a, 0x87, 0x95, 0x51, 0x3b, 0xb0,
	0x02, 0x19, 0x41, 0x33, 0xb4, 0x17, 0xbd, 0xea, 0x61, 0x65, 0xd4, 0x39, 0xe9, 0x5a, 0x84, 0x63,
	0xe7, 0xee, 0xcc, 0xfe, 0xe7, 0xb0, 0x37, 0x59, 0xea, 0x6b, 0x95, 0x88, 0x9f, 0x78, 0x8e, 0xfd,
	0xfd, 0x92, 0xa7, 0x3a, 0x83, 0xe6, 0x0b, 0x2a, 0x22, 0x07, 0x6d, 0x04, 0x32, 0x84, 0x56, 0x4c,
	0xd3, 0xf4, 0x85, 0x4a, 0x98, 0xc1, 0x6e, 0x07, 0xb9, 0xec, 0x7f, 0x0b, 0x7b, 0xe7, 0x4a, 0x4a,
	0x1e, 0xea, 0xe7, 0x3c, 0xb9, 0x11, 0x21, 0x9f, 0x48, 0xf6, 0x4c, 0x24, 0x89, 0x4a, 0xc8, 0x3e,
	0xb4, 0x17, 0xe6, 0x34, 0x13, 0xcc, 0x00, 0xd6, 0x83, 0x96, 0x55, 0x4c, 0x19, 0x79, 0x13, 0x3a,
	0x5c, 0xb2, 0x58, 0x09, 0xa9, 0x33, 0x73, 0xd5, 0x98, 0xc1, 0xa9, 0xa6, 0xcc, 0x3f, 0x85, 0xbe,
	0xc5, 0x79, 0x2a, 0x24, 0x73, 0xf9, 0xbd, 0x05, 0xdb, 0x61, 0x24, 0xb8, 0xd4, 0xb3, 0x62, 0x05,
	0x3a, 0x56, 0xf7, 0x75, 0xa6, 0xf2, 0x1f, 0x43, 0xcf, 0xfa, 0x5d, 0xf0, 0xe2, 0xb3, 0x22, 0xb1,
	0x10, 0x1a, 0xb3, 0xb0, 0x02, 0x19, 0x40, 0x43, 0xcd, 0xe7, 0x29, 0xd7, 0x18, 0x1d, 0x25, 0xff,
	0x23, 0x17, 0xd9, 0x20, 0x60, 0xd1, 0xdf, 0x86, 0xa6, 0xcd, 0x3d, 0xf5, 0x2a, 0x87, 0xb5, 0x51,
	0xe7, 0x64, 0x07, 0xcb, 0x6b, 0xaf, 0x06, 0xce, 0xea, 0x4f, 0xa0, 0x8f, 0x95, 0xf8, 0xdf, 0x09,
	0x3c, 0x06, 0x52, 0x84, 0xc0, 0x0c, 0x8e, 0xa0, 0x95, 0x5a, 0xad, 0x4b, 0xc1, 0x31, 0x8c, 0x97,
	0x83, 0xdc, 0xee, 0x2f, 0xa1, 0x89, 0xcc, 0x92, 0x2e, 0x54, 0xf3, 0xf2, 0x57, 0x05, 0x23, 0x04,
	0xb6, 0x24, 0x5d, 0x70, 0x24, 0xd2, 0x9c, 0x57, 0xb4, 0xd7, 0xee, 0xa2, 0x7d, 0xab, 0x4c, 0x7b,
	0xe6, 0x41, 0xd9, 0x42, 0x48, 0xaf, 0x7e, 0x58, 0x19, 0xb5, 0x02, 0x2b, 0xf8, 0x3f, 0x40, 0x13,
	0x73, 0xb9, 0x57, 0x58, 0x0f, 0x9a, 0xa9, 0x56, 0x09, 0xbd, 0xe2, 0x26, 0x70, 0x2d, 0x70, 0x22,
	0x19, 0xc3, 0xae, 0x4e, 0xe8, 0x7c, 0x2e, 0xc2, 0x59, 0xa8, 0x64, 0xba, 0x5c, 0xc4, 0xd9, 0x4c,
	0x98, 0x2c, 0x6a, 0x01, 0x41, 0xd3, 0xf9, 0xca, 0xe2, 0xff, 0x56, 0x83, 0x06, 0xb6, 0xdd, 0x7a,
	0xe4, 0xd7, 0x01, 0xb0, 0xf3, 0x57, 0x8d, 0xd6, 0x46, 0xcd, 0xd4, 0x24, 0x26, 0xe2, 0x9b, 0x0f,
	0xf0, 0xe9, 0xe6, 0x8c, 0xba, 0x53, 0x7c, 0xb5, 0x39, 0xe7, 0x0f, 0xa8, 0x17, 0x1e, 0x30, 0x80,
	0x06, 0x53, 0x0b, 0x2a, 0xa4, 0xd7, 0x30, 0x5a, 0x94, 0x36, 0xda, 0xb4, 0xb9, 0xd1, 0xa6, 0x26,
	0xab, 0x84, 0x53, 0xcd, 0xd9, 0x8c, 0x6a, 0xaf, 0x65, 0x1e, 0xd6, 0x46, 0xcd, 0x44, 0x93, 0x03,
	0x68, 0x5f, 0x52, 0xc9, 0x5e, 0x08, 0xa6, 0xaf, 0xbd, 0xb6, 0xb5, 0xe6, 0x8a, 0xac, 0x70, 0x58,
	0x03, 0x0f, 0x6c, 0xe1, 0x50, 0x24, 0xef, 0x40, 0x9f, 0xde, 0x50, 0x11, 0xd1, 0xcb, 0x88, 0xcf,
	0x5c, 0x71, 0x3b, 0xe6, 0x4e, 0x2f, 0x37, 0x3c, 0xc7, 0x2a, 0x8f, 0xa0, 0x89, 0x1d, 0xe3, 0x6d,
	0x97, 0x56, 0x86, 0x6b, 0x28, 0x67, 0x26, 0x1f, 0x42, 0x0f, 0x8f, 0x33, 0x37, 0xa2, 0xde, 0x8e,
	0x71, 0x59, 0x1b, 0x83, 0x07, 0x78, 0xed, 0x53, 0xbc, 0x95, 0x25, 0x14, 0xa9, 0x90, 0x46, 0x33,
	0xc6, 0x53, 0x2d, 0xa4, 0xd9, 0x6d, 0x5e, 0xd7, 0xd4, 0xa3, 0x67, 0x0c, 0x9f, 0xac, 0xf4, 0x27,
	0x7f, 0x54, 0xa1, 0x8b, 0x7d, 0xeb, 0xfa, 0x68, 0x0a, 0x8d, 0x73, 0x53, 0x15, 0xb2, 0xb6, 0xcf,
	0x86, 0x83, 0xb5, 0xfd, 0x86, 0x73, 0xe2, 0xef, 0xfd, 0xfc, 0xfb, 0x9f, 0xbf, 0x54, 0xfb, 0xfe,
	0xf6, 0xf8, 0xe6, 0xbd, 0x31, 0xf2, 0x9c, 0x9e, 0x55, 0x8e, 0xc8, 0x17, 0xd0, 0xf8, 0x26, 0x66,
	0xff, 0x05, 0xea, 0xc0, 0x40, 0x0d, 0x86, 0xfd, 0x22, 0xd4, 0x38, 0xe5, 0xd1, 0x3c, 0xc3, 0xfb,
	0x0c, 0x6a, 0x17, 0x5c, 0xdf, 0x1b, 0xec, 0x91, 0x01, 0xdb, 0x25, 0x9b, 0x60, 0x84, 0x42, 0x3b,
	0xdf, 0xc8, 0xe4, 0x0d, 0xf4, 0xbf, 0x63, 0x47, 0xbf, 0x2a, 0x59, 0xbf, 0x8c, 0x4f, 0x97, 0xfa,
	0xfa, 0xac, 0x72, 0x74, 0xf2, 0x57, 0x0d, 0x76, 0x2c, 0x47, 0xae, 0xb2, 0xcf, 0x6c, 0xfa, 0x7b,
	0x25, 0x02, 0x57, 0x3b, 0x6b, 0xe8, 0x6d, 0x1a, 0x30, 0xd2, 0xae, 0x89, 0xb4, 0x43, 0x3a, 0x59,
	0x24, 0xdc, 0x7b, 0x64, 0x0a, 0x5b, 0xd9, 0xa6, 0x26, 0x65, 0xb7, 0xc2, 0xf2, 0x1e, 0x96, 0x5b,
	0xc5, 0xf7, 0x0c, 0x0a, 0x21, 0xbd, 0x02, 0x8a, 0x2d, 0xc7, 0x13, 0x68, 0x65, 0x7e, 0x4f, 0x7e,
	0x9c, 0x32, 0x52, 0x76, 0xba, 0x17, 0xc6, 0x4b, 0xc1, 0x6e, 0xc9, 0x05, 0x80, 0x25, 0xfb, 0x1e,
	0x28, 0xfb, 0x06, 0xe5, 0x35, 0x7f, 0x03, 0x25, 0x63, 0x39, 0x36, 0xab, 0x34, 0xfb, 0xc1, 0xe5,
	0xcc, 0xdc, 0xf1, 0xc3, 0x5b, 0x87, 0x3d, 0x35, 0xb0, 0xef, 0x0e, 0x8f, 0x4b, 0xb0, 0xf9, 0x2f,
	0xf1, 0x76, 0xec, 0x46, 0x69, 0xfc, 0xb2, 0xf0, 0x2b, 0xbc, 0x25, 0x1f, 0xe7, 0x2d, 0xff, 0xef,
	0x69, 0x0f, 0x0c, 0x7e, 0xcf, 0x2f, 0xd2, 0x90, 0x51, 0xfd, 0x6b, 0x15, 0xba, 0x98, 0x9b, 0xe3,
	0xfa, 0x4b, 0xcb, 0xb5, 0x57, 0x9e, 0xef, 0x02, 0xd9, 0x8f, 0xfe, 0xc1, 0x82, 0x6c, 0x3f, 0x34,
	0x61, 0xba, 0xc4, 0xcc, 0x93, 0xfb, 0xc3, 0x90, 0xa7, 0x1b, 0xc3, 0x84, 0xae, 0xc3, 0x35, 0xb9,
	0xdc, 0x97, 0xce, 0x3f, 0x2f, 0xef, 0x04, 0xdb, 0xe6, 0x55, 0x28, 0xa5, 0xe9, 0x29, 0xa1, 0x90,
	0xc9, 0xc6, 0x8a, 0xb8, 0x0b, 0xa4, 0xb4, 0x1a, 0x1c, 0xc8, 0x59, 0xe5, 0xe8, 0xb2, 0x61, 0xee,
	0xbd, 0xff, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x0a, 0xc0, 0x76, 0xb0, 0x09, 0x00, 0x00,
}
